# Generated by Django 4.1.1 on 2023-02-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='account_icons/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='introduce',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
